
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.chara
{ 
    public enum ESkinEquipType
    {
        /// <summary>
        /// 头部
        /// </summary>
        Head = 0,
        /// <summary>
        /// 头发
        /// </summary>
        Hair = 1,
        /// <summary>
        /// 眼睛
        /// </summary>
        Eye = 2,
        /// <summary>
        /// 眼镜
        /// </summary>
        Glasses = 3,
        /// <summary>
        /// 口部
        /// </summary>
        Mouth = 4,
        /// <summary>
        /// 脖子
        /// </summary>
        Neck = 5,
        /// <summary>
        /// 内衣(上)
        /// </summary>
        UnderWear_Up = 6,
        /// <summary>
        /// 内衣(下)
        /// </summary>
        UnderWear_Down = 7,
        /// <summary>
        /// 上衣
        /// </summary>
        Clouth = 8,
        /// <summary>
        /// 裤子
        /// </summary>
        Pants = 9,
        /// <summary>
        /// 鞋子
        /// </summary>
        Shoes = 10,
        /// <summary>
        /// 袜子
        /// </summary>
        Socks = 11,
        /// <summary>
        /// 手部
        /// </summary>
        Hand = 12,
        /// <summary>
        /// 包
        /// </summary>
        Bag = 13,
        /// <summary>
        /// 武器
        /// </summary>
        Weapon = 14,
    }

} 

