
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.chara
{ 
    /// <summary>
    /// 角色外表类型
    /// </summary>
    public enum ESkinType
    {
        /// <summary>
        /// 性别
        /// </summary>
        Gender = 0,
        /// <summary>
        /// 前发
        /// </summary>
        Hair_Front = 1,
        /// <summary>
        /// 中发
        /// </summary>
        Hair_Middle = 2,
        /// <summary>
        /// 后发
        /// </summary>
        Hair_Back = 3,
        /// <summary>
        /// 眼睛
        /// </summary>
        Eye = 4,
        /// <summary>
        /// 眉毛
        /// </summary>
        Eyebrow = 5,
        /// <summary>
        /// 鼻子
        /// </summary>
        Noise = 6,
        /// <summary>
        /// 嘴
        /// </summary>
        Mouth = 7,
        /// <summary>
        /// 肤色
        /// </summary>
        SkinColor = 8,
        /// <summary>
        /// 身材
        /// </summary>
        Figure = 9,
        /// <summary>
        /// 身高
        /// </summary>
        Height = 10,
    }

} 

