
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class dialogue_story : Luban.BeanBase
{
    public dialogue_story(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["storyName"].IsString) { throw new SerializationException(); }  StoryName = _buf["storyName"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
    }

    public static dialogue_story Deserializedialogue_story(JSONNode _buf)
    {
        return new dialogue_story(_buf);
    }

    public readonly int Id;
    public readonly string StoryName;
    public readonly string Desc;
   
    public const int __ID__ = 1576170446;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "storyName:" + StoryName + ","
        + "desc:" + Desc + ","
        + "}";
    }
}

}
