
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.dialogue
{
public partial class TbStory
{
    private readonly System.Collections.Generic.Dictionary<int, dialogue_story> _dataMap;
    private readonly System.Collections.Generic.List<dialogue_story> _dataList;
    
    public TbStory(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, dialogue_story>();
        _dataList = new System.Collections.Generic.List<dialogue_story>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            dialogue_story _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = dialogue_story.Deserializedialogue_story(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, dialogue_story> DataMap => _dataMap;
    public System.Collections.Generic.List<dialogue_story> DataList => _dataList;

    public dialogue_story GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public dialogue_story Get(int key) => _dataMap[key];
    public dialogue_story this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
