
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class game_save_index : Luban.BeanBase
{
    public game_save_index(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["saveDataName"].IsString) { throw new SerializationException(); }  SaveDataName = _buf["saveDataName"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
    }

    public static game_save_index Deserializegame_save_index(JSONNode _buf)
    {
        return new game_save_index(_buf);
    }

    /// <summary>
    /// 索引
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 存档数据字段名
    /// </summary>
    public readonly string SaveDataName;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
   
    public const int __ID__ = -407700995;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "saveDataName:" + SaveDataName + ","
        + "desc:" + Desc + ","
        + "}";
    }
}

}
