
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class game_process : Luban.BeanBase
{
    public game_process(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (game.EPlotType)_buf["type"].AsInt; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
    }

    public static game_process Deserializegame_process(JSONNode _buf)
    {
        return new game_process(_buf);
    }

    /// <summary>
    /// 索引
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 流程节点名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 流程类型
    /// </summary>
    public readonly game.EPlotType Type;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
   
    public const int __ID__ = 2139291426;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "type:" + Type + ","
        + "desc:" + Desc + ","
        + "}";
    }
}

}
