
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.game
{ 
    /// <summary>
    /// 流程
    /// </summary>
    public enum EProcessState
    {
        /// <summary>
        /// 开始
        /// </summary>
        StartGame = 0,
        /// <summary>
        /// 捏人
        /// </summary>
        CharaMake = 1,
        /// <summary>
        /// 游戏
        /// </summary>
        Game = 2,
    }

} 

