
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.game
{
public partial class TbGameProcess
{
    private readonly System.Collections.Generic.Dictionary<int, game_process> _dataMap;
    private readonly System.Collections.Generic.List<game_process> _dataList;
    
    public TbGameProcess(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, game_process>();
        _dataList = new System.Collections.Generic.List<game_process>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            game_process _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = game_process.Deserializegame_process(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, game_process> DataMap => _dataMap;
    public System.Collections.Generic.List<game_process> DataList => _dataList;

    public game_process GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public game_process Get(int key) => _dataMap[key];
    public game_process this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
