
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.game
{ 
    public enum EPlotType
    {
        /// <summary>
        /// 开始
        /// </summary>
        START = 0,
        /// <summary>
        /// 剧情过场
        /// </summary>
        STORY = 1,
        /// <summary>
        /// 玩家游玩
        /// </summary>
        GAME = 2,
        /// <summary>
        /// 互动道具或人物产生的对话
        /// </summary>
        Dialogue = 3,
    }

} 

