
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.inquiry
{
public partial class TbExhibit
{
    private readonly System.Collections.Generic.Dictionary<string, inquiry_exhibit> _dataMap;
    private readonly System.Collections.Generic.List<inquiry_exhibit> _dataList;
    
    public TbExhibit(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, inquiry_exhibit>();
        _dataList = new System.Collections.Generic.List<inquiry_exhibit>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            inquiry_exhibit _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = inquiry_exhibit.Deserializeinquiry_exhibit(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, inquiry_exhibit> DataMap => _dataMap;
    public System.Collections.Generic.List<inquiry_exhibit> DataList => _dataList;

    public inquiry_exhibit GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public inquiry_exhibit Get(string key) => _dataMap[key];
    public inquiry_exhibit this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
