
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.inquiry
{ 
    public enum EInquiryType
    {
        /// <summary>
        /// 证物
        /// </summary>
        Exhibit = 0,
        /// <summary>
        /// 证言
        /// </summary>
        Testimony = 1,
        /// <summary>
        /// 人物
        /// </summary>
        RelatedPersonnel = 2,
    }

} 

