
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class inquiry_exhibit : Luban.BeanBase
{
    public inquiry_exhibit(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsString) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["index"].IsNumber) { throw new SerializationException(); }  Index = _buf["index"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["case"].IsNumber) { throw new SerializationException(); }  Case = _buf["case"]; }
    }

    public static inquiry_exhibit Deserializeinquiry_exhibit(JSONNode _buf)
    {
        return new inquiry_exhibit(_buf);
    }

    public readonly string ID;
    public readonly int Index;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 对应案件
    /// </summary>
    public readonly int Case;
   
    public const int __ID__ = -515823327;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "index:" + Index + ","
        + "name:" + Name + ","
        + "case:" + Case + ","
        + "}";
    }
}

}
