
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.inquiry
{
public partial class TbPersonnel
{
    private readonly System.Collections.Generic.Dictionary<string, inquiry_personnel> _dataMap;
    private readonly System.Collections.Generic.List<inquiry_personnel> _dataList;
    
    public TbPersonnel(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, inquiry_personnel>();
        _dataList = new System.Collections.Generic.List<inquiry_personnel>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            inquiry_personnel _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = inquiry_personnel.Deserializeinquiry_personnel(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Index, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, inquiry_personnel> DataMap => _dataMap;
    public System.Collections.Generic.List<inquiry_personnel> DataList => _dataList;

    public inquiry_personnel GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public inquiry_personnel Get(string key) => _dataMap[key];
    public inquiry_personnel this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
