
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.item
{ 
    /// <summary>
    /// 道具类型
    /// </summary>
    public enum EType
    {
        /// <summary>
        /// 装备
        /// </summary>
        Equip = 0,
        /// <summary>
        /// 消耗道具
        /// </summary>
        Cosume = 1,
        /// <summary>
        /// 普通
        /// </summary>
        Normal = 2,
    }

} 

