
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.item
{
public partial class TbItem
{
    private readonly System.Collections.Generic.Dictionary<int, item_data> _dataMap;
    private readonly System.Collections.Generic.List<item_data> _dataList;
    
    public TbItem(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, item_data>();
        _dataList = new System.Collections.Generic.List<item_data>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            item_data _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = item_data.Deserializeitem_data(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Index, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, item_data> DataMap => _dataMap;
    public System.Collections.Generic.List<item_data> DataList => _dataList;

    public item_data GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public item_data Get(int key) => _dataMap[key];
    public item_data this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
