
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.save
{ 
    public enum ESaveDataType
    {
        /// <summary>
        /// 剧情，对话系统相关
        /// </summary>
        CurStoryStateSaveData = 1,
        /// <summary>
        /// 现有线索存档
        /// </summary>
        ExhibitSaveData = 2,
        /// <summary>
        /// 证言
        /// </summary>
        TestimonySaveData = 3,
        /// <summary>
        /// 人物
        /// </summary>
        PersonnelSaveData = 4,
    }

} 

