
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.save
{
public partial class TbStoryTypeSaveDataIndex
{
    private readonly System.Collections.Generic.Dictionary<int, game_save_index> _dataMap;
    private readonly System.Collections.Generic.List<game_save_index> _dataList;
    
    public TbStoryTypeSaveDataIndex(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, game_save_index>();
        _dataList = new System.Collections.Generic.List<game_save_index>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            game_save_index _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = game_save_index.Deserializegame_save_index(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, game_save_index> DataMap => _dataMap;
    public System.Collections.Generic.List<game_save_index> DataList => _dataList;

    public game_save_index GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public game_save_index Get(int key) => _dataMap[key];
    public game_save_index this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
